In [1]:
import numpy as np

In [2]:
X = np.array([[1,0,1,0], [1,0,1,1],[0,1,0,1]])
y = np.array([[1],[1],[0]])

In [3]:
X

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 0, 1]])

In [4]:
y

array([[1],
       [1],
       [0]])

In [5]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [6]:
def sigmoid_derivative(x):
    return x * (1 - x)

In [21]:
epochs = 20000
alpha = 0.01
inputNeurons = X.shape[1]
hiddenNeurons = 3
outputNeurons = 1

In [22]:
wh = np.random.uniform(size=(inputNeurons, hiddenNeurons))
bh = np.random.uniform(size=(1,hiddenNeurons))
wout = np.random.uniform(size=(hiddenNeurons, outputNeurons))
bout = np.random.uniform(size=(1,outputNeurons))

In [10]:
# Feedforward

# Input Layer -> Hidden Layer
fx = np.dot(X,wh) + bh
z = sigmoid(fx)

# Hidden Layer -> Output Layer
fx = np.dot(z,wout) + bout
z_out = sigmoid(fx)

In [11]:
fx

array([[2.03561904],
       [2.13365325],
       [2.04327168]])

In [12]:
z_out

array([[0.88448642],
       [0.89413132],
       [0.88526599]])

In [13]:
# Backpropagation

errorOutputLayer = y - z_out
slopeOutputLayer = sigmoid_derivative(z_out)
deltaOutputLayer = errorOutputLayer * slopeOutputLayer

errorHiddenLayer = deltaOutputLayer.dot(wout.T)
slopeHiddenLayer = sigmoid_derivative(z)
deltaHiddenLayer = errorHiddenLayer * slopeHiddenLayer

In [14]:
wout += z.T.dot(deltaOutputLayer) * alpha
bout += np.sum(deltaOutputLayer, axis=0, keepdims=True) * alpha
wh += X.T.dot(deltaHiddenLayer) * alpha
bh += np.sum(deltaHiddenLayer, axis=0, keepdims=True) * alpha

In [23]:
for i in range(epochs):
    # Feedforward

    # Input Layer -> Hidden Layer
    fx = np.dot(X,wh) + bh
    z = sigmoid(fx)

    # Hidden Layer -> Output Layer
    fx = np.dot(z,wout) + bout
    z_out = sigmoid(fx)
    
    # Backpropagation

    errorOutputLayer = y - z_out
    slopeOutputLayer = sigmoid_derivative(z_out)
    deltaOutputLayer = errorOutputLayer * slopeOutputLayer

    errorHiddenLayer = deltaOutputLayer.dot(wout.T)
    slopeHiddenLayer = sigmoid_derivative(z)
    deltaHiddenLayer = errorHiddenLayer * slopeHiddenLayer
    
    wout += z.T.dot(deltaOutputLayer) * alpha
    bout += np.sum(deltaOutputLayer, axis=0, keepdims=True) * alpha
    wh += X.T.dot(deltaHiddenLayer) * alpha
    bh += np.sum(deltaHiddenLayer, axis=0, keepdims=True) * alpha


In [24]:
z_out

array([[0.96469836],
       [0.9474319 ],
       [0.0713563 ]])