In [1]:
import tensorflow as tf

In [2]:
x = tf.Variable(5)
y = tf.Variable(6)

In [3]:
# eager execution
x + y

<tf.Tensor: shape=(), dtype=int32, numpy=11>

In [4]:
tf.ones((4,4))

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [5]:
tf.ones((4,4)) + 5

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]], dtype=float32)>