In [1]:
import numpy as np

In [2]:
x = np.array([[1,0,1,0],[1,0,1,1],[0,1,1,1]])
y = np.array([[1],[1],[0]])

In [3]:
x

array([[1, 0, 1, 0],
       [1, 0, 1, 1],
       [0, 1, 1, 1]])

In [4]:
y

array([[1],
       [1],
       [0]])

In [5]:
def signoid(x):
    return 1 / (1 + np.exp(-x))

In [6]:
def signoid_derivative(x):
    return x * (1 - x)

In [7]:
x.shape[1]    # columns

4

In [8]:
epochs = 20000
alpha = 0.01
inputNeurons = x.shape[1]
hiddenNeurons = 3
outputNeurons = 1

In [9]:
wh = np.random.uniform(size=(inputNeurons, hiddenNeurons)) #(4,3)
bh = np.random.uniform(size=(1, hiddenNeurons))   #(1,3)
wout = np.random.uniform(size=(hiddenNeurons, outputNeurons))    #(3,1)
bout = np.random.uniform(size=(1, outputNeurons))    #(1,1)

In [10]:
#    Input Layer -> Hidden Layer

fx = np.dot(x,wh) + bh
z = signoid(fx)

#    Hidden Layer -> Output Layer

fx = np.dot(z,wout) + bout
z_out = signoid(fx)

In [11]:
fx

array([[2.00658295],
       [2.10195094],
       [2.10880106]])

In [12]:
z_out

array([[0.88148652],
       [0.89109265],
       [0.89175566]])

In [13]:
#  Back Propagataion

errorOutputLayer = y - z_out
slopeOutputLayer = signoid_derivative(z_out)
deltaOutputLayer = errorOutputLayer * slopeOutputLayer

errorHiddenLayer = deltaOutputLayer.dot(wout.T)
slopeHiddenLayer = signoid_derivative(z)
deltaHiddenLayer = errorHiddenLayer * slopeHiddenLayer


In [17]:
wout += z.T.dot(deltaOutputLayer)  * alpha
bout += np.sum(deltaOutputLayer,  axis=0 , keepdims=True ) * alpha
wh += x.T.dot(deltaHiddenLayer) * alpha
bh += np.sum(deltaHiddenLayer, axis=0 , keepdims=True) * alpha

In [18]:
for i in range(epochs):

    fx = np.dot(x,wh) + bh
    z = signoid(fx)

    fx = np.dot(z,wout) + bout
    z_out = signoid(fx)
    
    errorOutputLayer = y - z_out
    slopeOutputLayer = signoid_derivative(z_out)
    deltaOutputLayer = errorOutputLayer * slopeOutputLayer

    errorHiddenLayer = deltaOutputLayer.dot(wout.T)
    slopeHiddenLayer = signoid_derivative(z)
    deltaHiddenLayer = errorHiddenLayer * slopeHiddenLayer

    
    wout += z.T.dot(deltaOutputLayer)  * alpha
    bout += np.sum(deltaOutputLayer,  axis=0  , keepdims=True) * alpha
    wh += x.T.dot(deltaHiddenLayer) * alpha
    bh += np.sum(deltaHiddenLayer, axis=0 , keepdims=True) * alpha

In [19]:
z_out

array([[0.97822729],
       [0.96258765],
       [0.04428877]])